version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Ubah ke port 3000
    environment:
      - VITE_HOST=0.0.0.0  # Pastikan host diatur ke 0.0.0.0
    command: npm run dev
